server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: file-mover-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: file-mover
          app: file-mover
          env: development
          __path__: /logs/*.log

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+ \S+) \[(?P<thread>[^\]]+)\] \[(?P<traceId>[^\]]+)\] (?P<level>\w+)\s+(?P<logger>\S+) - (?P<message>.*)$'
      - labels:
          level:
          traceId:
          logger:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'
